package cn.gyyx.training.beans;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account_bind_log
 *
 * @mbggenerated do_not_delete_during_merge Wed Jul 27 21:34:29 CST 2016
 */
public class AccountBindLog {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.code
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private Integer code;

    /**
     * Database Column Remarks:
     *   用户主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.user_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private Integer userId;

    /**
     * Database Column Remarks:
     *   账户
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.account
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String account;

    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.phone_num
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String phoneNum;

    /**
     * Database Column Remarks:
     *   绑定IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.bind_ip
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private Integer bindIp;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.create_time
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   设备标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.device_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String deviceId;

    /**
     * Database Column Remarks:
     *   手机MAC
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.mac_address
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String macAddress;

    /**
     * Database Column Remarks:
     *   移动设备标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.imei
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String imei;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.ifa
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String ifa;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.ifv
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String ifv;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.ios_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String iosId;

    /**
     * Database Column Remarks:
     *   系统类型ios android
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.os_type
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String osType;

    /**
     * Database Column Remarks:
     *   系统版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.os_version
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String osVersion;

    /**
     * Database Column Remarks:
     *   分辨率
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.resolution
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String resolution;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.operators
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String operators;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.phone_ram
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String phoneRam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bind_log.device_model
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    private String deviceModel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.code
     *
     * @return the value of account_bind_log.code
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.code
     *
     * @param code the value for account_bind_log.code
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.user_id
     *
     * @return the value of account_bind_log.user_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.user_id
     *
     * @param userId the value for account_bind_log.user_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.account
     *
     * @return the value of account_bind_log.account
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.account
     *
     * @param account the value for account_bind_log.account
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.phone_num
     *
     * @return the value of account_bind_log.phone_num
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getPhoneNum() {
        return phoneNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.phone_num
     *
     * @param phoneNum the value for account_bind_log.phone_num
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setPhoneNum(String phoneNum) {
        this.phoneNum = phoneNum == null ? null : phoneNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.bind_ip
     *
     * @return the value of account_bind_log.bind_ip
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public Integer getBindIp() {
        return bindIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.bind_ip
     *
     * @param bindIp the value for account_bind_log.bind_ip
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setBindIp(Integer bindIp) {
        this.bindIp = bindIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.create_time
     *
     * @return the value of account_bind_log.create_time
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.create_time
     *
     * @param createTime the value for account_bind_log.create_time
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.device_id
     *
     * @return the value of account_bind_log.device_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getDeviceId() {
        return deviceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.device_id
     *
     * @param deviceId the value for account_bind_log.device_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId == null ? null : deviceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.mac_address
     *
     * @return the value of account_bind_log.mac_address
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getMacAddress() {
        return macAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.mac_address
     *
     * @param macAddress the value for account_bind_log.mac_address
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress == null ? null : macAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.imei
     *
     * @return the value of account_bind_log.imei
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getImei() {
        return imei;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.imei
     *
     * @param imei the value for account_bind_log.imei
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setImei(String imei) {
        this.imei = imei == null ? null : imei.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.ifa
     *
     * @return the value of account_bind_log.ifa
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getIfa() {
        return ifa;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.ifa
     *
     * @param ifa the value for account_bind_log.ifa
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setIfa(String ifa) {
        this.ifa = ifa == null ? null : ifa.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.ifv
     *
     * @return the value of account_bind_log.ifv
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getIfv() {
        return ifv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.ifv
     *
     * @param ifv the value for account_bind_log.ifv
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setIfv(String ifv) {
        this.ifv = ifv == null ? null : ifv.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.ios_id
     *
     * @return the value of account_bind_log.ios_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getIosId() {
        return iosId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.ios_id
     *
     * @param iosId the value for account_bind_log.ios_id
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setIosId(String iosId) {
        this.iosId = iosId == null ? null : iosId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.os_type
     *
     * @return the value of account_bind_log.os_type
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getOsType() {
        return osType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.os_type
     *
     * @param osType the value for account_bind_log.os_type
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setOsType(String osType) {
        this.osType = osType == null ? null : osType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.os_version
     *
     * @return the value of account_bind_log.os_version
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getOsVersion() {
        return osVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.os_version
     *
     * @param osVersion the value for account_bind_log.os_version
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setOsVersion(String osVersion) {
        this.osVersion = osVersion == null ? null : osVersion.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.resolution
     *
     * @return the value of account_bind_log.resolution
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getResolution() {
        return resolution;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.resolution
     *
     * @param resolution the value for account_bind_log.resolution
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setResolution(String resolution) {
        this.resolution = resolution == null ? null : resolution.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.operators
     *
     * @return the value of account_bind_log.operators
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getOperators() {
        return operators;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.operators
     *
     * @param operators the value for account_bind_log.operators
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setOperators(String operators) {
        this.operators = operators == null ? null : operators.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.phone_ram
     *
     * @return the value of account_bind_log.phone_ram
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getPhoneRam() {
        return phoneRam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.phone_ram
     *
     * @param phoneRam the value for account_bind_log.phone_ram
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setPhoneRam(String phoneRam) {
        this.phoneRam = phoneRam == null ? null : phoneRam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bind_log.device_model
     *
     * @return the value of account_bind_log.device_model
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public String getDeviceModel() {
        return deviceModel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bind_log.device_model
     *
     * @param deviceModel the value for account_bind_log.device_model
     *
     * @mbggenerated Wed Jul 27 21:34:29 CST 2016
     */
    public void setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel == null ? null : deviceModel.trim();
    }
}